name: microsoft-azure-servicebus-emulator
services:
  node-process:
    container_name: "node-process"
    build:
      context: ./node-process
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DB_ATLAS_URI: mongodb://development:@Sqledge123$2025@localhost:27017/?directConnection=true
    networks:
      - sb-emulator
    depends_on:
      - servicebus-emulator
      - eventhubs-emulator
  node-api-mongo:
    container_name: "node-api-mongo"
    build:
      context: ./node-api-mongo
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    networks:
      - sb-emulator
    depends_on:
      - servicebus-emulator
      - eventhubs-emulator
      - mongodb
  servicebus-emulator:
    container_name: "servicebus-emulator"
    image: mcr.microsoft.com/azure-messaging/servicebus-emulator:latest
    pull_policy: always
    volumes:
      - "${CONFIG_PATH_SB}:/ServiceBus_Emulator/ConfigFiles/Config.json"
    ports:
      - "5672:5672"
    environment:
      SQL_SERVER: sqledge
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}"  # Password should be same as what is set for SQL Edge  
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - sqledge
    networks:
      sb-emulator:
        aliases:
          - "servicebus-emulator"
  sqledge:
    container_name: "sqledge"
    image: "mcr.microsoft.com/azure-sql-edge:latest"
    networks:
      sb-emulator:
        aliases:
          - "sqledge"
    environment:
      ACCEPT_EULA: ${ACCEPT_EULA}
      MSSQL_SA_PASSWORD: "${SQL_PASSWORD}" # To be filled by user as per policy : https://learn.microsoft.com/en-us/sql/relational-databases/security/strong-passwords?view=sql-server-linux-ver16 
  eventhubs-emulator:
    container_name: "eventhubs-emulator"
    image: "mcr.microsoft.com/azure-messaging/eventhubs-emulator:latest"
    pull_policy: always
    volumes:
      - "${CONFIG_PATH_EH}:/Eventhubs_Emulator/ConfigFiles/Config.json"
    ports:
      - "5673:5673"
      - "9092:9092"
    environment:
      BLOB_SERVER: azurite
      METADATA_SERVER: azurite
      ACCEPT_EULA: ${ACCEPT_EULA}
    depends_on:
      - azurite
    networks:
      sb-emulator:
        aliases:
          - "eventhubs-emulator"
  azurite:
    container_name: "azurite"
    image: "mcr.microsoft.com/azure-storage/azurite:latest"
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    networks:
      sb-emulator:
        aliases:
          - "azurite"
 
#docker run -e MONGODB_INITDB_ROOT_USERNAME=user -e MONGODB_INITDB_ROOT_PASSWORD=pass -p 27017:27017 mongodb/mongodb-atlas-local
  atlas:
    image: mongodb/mongodb-atlas-local:latest
    ports:
        - 27017:27017
    environment:
        MONGODB_INITDB_ROOT_USERNAME: development
        MONGODB_INITDB_ROOT_PASSWORD: "@Sqledge123$2025"
        DB_ATLAS_URI: mongodb://development:@Sqledge123$2025@localhost:27017/?directConnection=true
    volumes:
      - mongo_data:/data/db
    networks:
      sb-emulator:
        aliases:
          - "atlas"
  
  mongodb:
    image: mongodb/mongodb-atlas-local
    environment:
        MONGODB_INITDB_ROOT_USERNAME: development
        MONGODB_INITDB_ROOT_PASSWORD: "@Sqledge123$2025"
    ports:
      - 27018:27017
    networks:
      sb-emulator:
        aliases:
          - "mongodb"
volumes:
  mongo_data:
networks:
  sb-emulator:
