services:
  iep-service:
    container_name: "iep-service"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3001:3000
    environment:
      DB_ATLAS_URI: ${DB_ATLAS_URI}
    networks:
      - iep_emulator
    depends_on:
      - mongodb
  mongodb:
    hostname: mongodb
    image: mongodb/mongodb-atlas-local
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${DB_ATLAS_MONGO_ADMIN_USER}
      MONGODB_INITDB_ROOT_PASSWORD: ${DB_ATLAS_MONGO_ADMIN_PASSWORD}
    ports:
      - 27017:27017
    # volumes:
    #   - data:/data/db
    #   - config:/data/configdb
    networks:
      - iep_emulator
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
      ME_CONFIG_MONGODB_SERVER: ${ME_CONFIG_MONGODB_SERVER}
    depends_on:
      - "mongodb"
    networks:
      - iep_emulator

volumes:
  data:
  config:

networks:
  iep_emulator:
    driver: bridge