openapi: 3.0.1
info:
  title:  IEP Program Management
  description:  IEP Program Management Service
  version: 1.0.0
  contact:
      name: HealthEquity Developer Portal
      url: https://developer.healthequity.com
servers:
  - url: https://api.sandbox.healthequity.com/iep/program-management/v1
    description: Development Sandbox Testing Environment
  - url: https://api.integration.testing.healthequity.com/iep/program-management/v1
    description: Integration Testing Environment
  - url: https://api.healthequity.com/iep/program-management/v1
    description: Production Environment
x-domain: program-management
x-sub-domain: program
tags:
  - name: Programs
  - name: Business Goals
  - name: Plans
  - name: Plan Goals
  - name: Templates
paths:
  # Program: Create
  /programs:
    post:
      summary: Create Program
      description:  Creates a new Program.
      operationId: createProgram
      tags:
        - Programs
      security:
        - OAuth2: ['write:program']
  # Program: Get
  /programs/{programId}:
    get:
      summary: Get Program by Id
      description: Get Program by Id
      operationId: getProgram
      tags:
        - Programs
      security:
        - OAuth2: ['read:program']
  # Program: Get All
  /programs/client/{clientId}:
    get:
      summary: Get All Programs of Client
      description: Get all Programs for a Client.
      operationId: getAllProgramsOfClient
      tags:
        - Programs
      security:
        - OAuth2: ['read:program']
  
  # BusinessGoal: Create & Get All
  /programs/{programId}/businessgoals:
    post:
      summary: Create BusinessGoal from Template
      description: Create BusinessGoal within a Program from a template
      operationId: createBusinessGoal
      tags:
        - Business Goals
      security:
        - OAuth2: ['write:businessGoal']
    get:
      summary: Get All BusinessGoals of Program
      description: Get all BusinessGoals for a Program.
      operationId: getAllBusinessGoalsOfProgram
      tags:
        - Business Goals
      security:
        - OAuth2: ['read:businessGoal']
  # BusinessGoal: Get
  /programs/{programId}/businessgoals/{businessGoalId}:
    get:
      summary: Get BusinessGoal by Id
      description: Get BusinessGoal by Id
      operationId: getBusinessGoalById
      tags:
        - Business Goals
      security:
        - OAuth2: ['read:businessGoal']

  # Plan: Create & Get All
  /plans:
    post:
      summary: Create Plan
      description:  Creates a new Plan in a Program.
      operationId: createPlan
      tags:
        - Plans
      security:
        - OAuth2: ['write:plan']
    get:
      summary: Get All Plans of Program
      description: Get all Plans for a Program.
      operationId: getAllPlansOfProgram
      tags:
        - Plans
      security:
        - OAuth2: ['read:plan']
  # Plan: Get
  /plans/{planId}:
    get:
      summary: Get Plan by Id
      description:  Get Plan by Id
      operationId: getPlanById
      tags:
        - Plans
      security:
        - OAuth2: ['read:plan']

  # PlanGoal: Create & Get All
  /plans/{planId}/goals:
    post:
      summary: Create PlanGoal from Template
      description:  Create a new PlanGoal from Template
      operationId: createPlanGoal
      tags:
        - Plan Goals
      security:
        - OAuth2: ['write:planGoal']
    get:
      summary: Get All PlanGoals of Plan
      description: Get All PlanGoals of Plan
      operationId: getAllPlanGoalsOfPlan
      tags:
        - Plan Goals
      security:
        - OAuth2: ['read:planGoal']
  # PlanGoal: Get
  /plans/{planId}/goals/{planGoalId}:
    get:
      summary: Get PlanGoal by Id
      description: Get PlanGoal by Id
      operationId: getPlanGoalById
      tags:
        - Plan Goals
      security:
        - OAuth2: ['read:planGoal']

  # BusinessGoalTemplate: Create & Get All
  /templates/businessgoals:
    post:
      summary: Create BusinessGoalTemplate
      description:  Creates a new BusinessGoalTemplate.
      operationId: createBusinessGoalTemplate
      tags:
        - Templates
      security:
        - OAuth2: ['write:businessGoalTemplate']
    get:
      summary: Get All BusinessGoalTemplates
      description: Get All Business Goal Templates
      operationId: getAllBusinessGoalTemplates
      tags:
        - Templates
      security:
        - OAuth2: ['read:businessGoalTemplate']
  # BusinessGoalTemplate: Get
  /templates/businessgoals/{businessGoalTemplateId}:
    get:
      summary: Get BusinessGoalTemplate by Id
      description: Get Business Goal Template by Id
      operationId: getBusinessGoalTemplateById
      tags:
        - Templates
      security:
        - OAuth2: ['read:businessGoalTemplate']

  # PlanGoalTemplate: Create & Get All
  /templates/plangoals:
    post:
      summary: Create PlanGoalTemplate
      description:  Creates a new PlanGoalTemplate.
      operationId: createPlanGoalTemplate
      tags:
        - Templates
      security:
        - OAuth2: ['write:planGoalTemplate']
    get:
      summary: Get All PlanGoalTemplates
      description: Get All Plan Goal Templates
      operationId: getAllPlanGoalTemplates
      tags:
        - Templates
      security:
        - OAuth2: ['read:planGoalTemplate']
  # PlanGoalTemplate: Get
  /templates/plangoals/{planGoalTemplateId}:
    get:
      summary: Get PlanGoalTemplates by Id
      description: Get a Plan Goal Template by Id
      operationId: getPlanGoalTemplateById
      tags:
        - Templates
      security:
        - OAuth2: ['read:planGoalTemplate']

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://login.microsoftonline.com/c5d0ad88-8f93-43b8-9b7c-c8a3bb8e410a/oauth2/v2.0/token
          scopes:
            'read:program': Grants events read access
            'write:program': Grants events write access
            'read:businessGoal': Grants events read access
            'write:businessGoal': Grants events write access
            'read:plan': Grants events read access
            'write:plan': Grants events write access
            'read:planGoal': Grants events read access
            'write:planGoal': Grants events write access
            'read:businessGoalTemplate': Grants events read access
            'write:businessGoalTemplate': Grants events write access
            'read:planGoalTemplate': Grants events read access
            'write:planGoalTemplate': Grants events write access