# Call the api service auth endpoint
###
POST http://localhost:3000/
Content-Type: application/json

{
    "memberId": "Member Id",
    "partnerId": "Apple Health Kit",
    "activityType": "walking",
    "activityDescription": "simple walking activity",
    "activityCode": "STEPS",
    "memberActivity": 1000,
    "activityDate": "1/16/2025",
    "attestKind": "3rd-party",
    "signature": "test"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "memberId": 1
}

###
POST http://localhost:3000/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJtZW1iZXJJZCI6MSwiaWF0IjoxNzM3NzU4OTQ2LCJleHAiOjE3Mzc3NjI1NDZ9.aq4z_mVo_BIMR657U3CWRI8EOw3uK9ZwB0yaAbhdZLw
Content-Type: application/json

[
  {"partnerId": "Apple Health Kit", "memberActivity": 23424.0, "activityDescription": "simple walking activity", "activityDate": "01/10/2025", "activityType": "walking", "memberId": "1000", "activityCode": "STEPS"}, 
  {"memberId": "1000", "activityType": "walking", "activityDescription": "simple walking activity", "partnerId": "Apple Health Kit", "activityCode": "STEPS", "activityDate": "01/14/2025", "memberActivity": 122.0}, 
  {"activityDescription": "simple walking activity", "memberActivity": 11.0, "activityDate": "01/02/2025", "activityCode": "STEPS", "memberId": "1000", "activityType": "walking", "partnerId": "Apple Health Kit"},
    {"partnerId": "Apple Health Kit", "memberActivity": 111.0, "activityDate": "01/06/2025", "activityType": "walking", "memberId": "1000", "activityCode": "STEPS", "activityDescription": "simple walking activity"} 
]


###
{
    "memberId": "Member Id",
    "partnerId": "Apple Health Kit",
    "activityType": "walking",
    "activityDescription": "simple walking activity",
    "activityCode": "STEPS",
    "memberActivity": 1000,
    "activityDate": "1/16/2025",
    "attestKind": "3rd-party",
    "signature": "test"
}